In [56]:
#### 1. Import the numpy package under the name `np` (★☆☆)

import numpy as np



In [57]:

#### 2. Print the numpy version and the configuration (★☆☆)

from numpy.lib import NumpyVersion
NumpyVersion(np.__version__)

NumpyVersion(1.23.5)

In [58]:
#### 3. Create a null vector of size 10 (★☆☆)
y = np.arange(10, dtype=int)
np.zeros_like(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
#### 4. How to find the memory size of any array (★☆☆)
y.size

10

In [60]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.linspace??

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Source:   
@array_function_dispatch(_linspace_dispatcher)
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
             axis=0):
    """
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `

In [61]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [62]:

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
np.linspace(10,40)

array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

In [63]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
y=[1, 2, 3, 4, 5]
print(y)
y.reverse()
print(y)

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


In [64]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
x = np.array([[0, 1, 2], [3, 4, 5],[6 , 7 , 8]])
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)




#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)





#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)




In [66]:
#### 11. Create a 3x3 identity matrix (★☆☆)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
### 12. Create a 3x3x3 array with random values (★☆☆)
a = np.array(range(1, 28))
a.shape = (3, 3, 3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [68]:
### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
rng = np.random.default_rng()
y=rng.integers(low=0, high=10, size=9) 
y.reshape(3,3)


array([[8, 1, 9],
       [2, 7, 0],
       [4, 4, 3]])

In [69]:
y.max()

9

In [70]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
rng = np.random.default_rng()
y=rng.integers(low=0, high=10, size=30)
y.mean()

4.833333333333333

In [71]:

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
a=np.zeros((5,5))
b=np.ones((5,5))
np.add(a,b)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [73]:
#### 17. What is the result of the following expression? (★☆☆)

0 * np.nan

nan

In [74]:
np.nan == np.nan

False

In [75]:
np.inf > np.nan

False

In [76]:
np.nan - np.nan

nan

In [77]:

np.nan in set([np.nan])

True

In [78]:
0.3 == 3 * 0.1

False

In [79]:

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
x = np.arange(16).reshape((4,4))
np.diag(np.diag(x))     

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [80]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
c = np.array([1,0,1,0,1,0,1,0])
np.tile(c,(8,1))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [81]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
x = np.random.random((5,5))
y=x/25
y


array([[0.01620016, 0.01762438, 0.00865255, 0.02699792, 0.03139823],
       [0.01475922, 0.03461986, 0.00511299, 0.00568159, 0.019223  ],
       [0.02776213, 0.02307032, 0.0134567 , 0.00830603, 0.03948012],
       [0.0243799 , 0.00910163, 0.01366955, 0.00351442, 0.0037581 ],
       [0.02209394, 0.03826202, 0.02504236, 0.02899893, 0.03621379]])

In [82]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)
print(z)

[[0.08996115 0.62006987]
 [1.05097867 0.68439429]
 [0.91036472 0.96347092]
 [0.96000461 0.78539311]
 [0.24664203 0.4915601 ]]


In [83]:

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
test = np.arange(1,10)
neg=(test>3)&(test<8)
test[neg]*=-1
test

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9])

In [89]:
print(sum(range(5),-1))


10


In [88]:
#### 26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


In [94]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

# ```python
# Z**Z


# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z
# ```
7**7




16

In [98]:
2 << 5 >> 2
2<<5
5>>2
2<<5>>2

16

In [ ]:
#### 28. What are the result of the following expressions? (★☆☆)
np.array([np.nan]).astype(int).astype(float)

np.array(0) // np.array(0)


In [108]:
x=np.array(9) 
x
np.array(0) / np.array(0)

/tmp/ipykernel_298/3775913643.py:3: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [109]:
np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [114]:
#### 30. How to find common values between two arrays? (★☆☆)
A = [1,2,3,4,6,4,4,5,3]
B=[1,3,4,5,6,7]
list(set(A).intersection(B))

[1, 3, 4, 5, 6]