In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)

import numpy as np



In [3]:

#### 2. Print the numpy version and the configuration (★☆☆)

from numpy.lib import NumpyVersion
NumpyVersion(np.__version__)

NumpyVersion(1.23.5)

In [4]:
#### 3. Create a null vector of size 10 (★☆☆)
y = np.arange(10, dtype=int)
np.zeros_like(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
#### 4. How to find the memory size of any array (★☆☆)
y.size

10

In [6]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.linspace??

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Source:   
@array_function_dispatch(_linspace_dispatcher)
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
             axis=0):
    """
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `

In [7]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [8]:

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
np.linspace(10,40)

array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

In [9]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
y=[1, 2, 3, 4, 5]
print(y)
y.reverse()
print(y)

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


In [10]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
x = np.array([[0, 1, 2], [3, 4, 5],[6 , 7 , 8]])
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)




#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)





#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)


In [12]:
#### 11. Create a 3x3 identity matrix (★☆☆)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
### 12. Create a 3x3x3 array with random values (★☆☆)
a = np.array(range(1, 28))
a.shape = (3, 3, 3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [14]:
### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
rng = np.random.default_rng()
y=rng.integers(low=0, high=10, size=9) 
y.reshape(3,3)


array([[8, 2, 3],
       [2, 4, 6],
       [5, 5, 7]])

In [15]:
y.max()

8

In [16]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
rng = np.random.default_rng()
y=rng.integers(low=0, high=10, size=30)
y.mean()

4.366666666666666

In [17]:

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
a=np.zeros((5,5))
b=np.ones((5,5))
np.add(a,b)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
#### 17. What is the result of the following expression? (★☆☆)

0 * np.nan

nan

In [20]:
np.nan == np.nan

False

In [21]:
np.inf > np.nan

False

In [22]:
np.nan - np.nan

nan

In [23]:

np.nan in set([np.nan])

True

In [24]:
0.3 == 3 * 0.1

False

In [25]:

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
x = np.arange(16).reshape((4,4))
np.diag(np.diag(x))     

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [26]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
c = np.array([1,0,1,0,1,0,1,0])
np.tile(c,(8,1))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [32]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
x = np.random.random((5,5))
y=x/25
y


array([[0.0106054 , 0.02794234, 0.02393312, 0.03152044, 0.01775478],
       [0.01899242, 0.01761372, 0.00011441, 0.03419324, 0.00747534],
       [0.02294575, 0.03094591, 0.0317311 , 0.03030703, 0.03453219],
       [0.01858381, 0.03060029, 0.01914681, 0.0225564 , 0.03032442],
       [0.01887831, 0.03657332, 0.01245652, 0.01522535, 0.03993858]])

In [28]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)
print(z)

[[1.87290616 0.91222249]
 [1.05334265 0.57194972]
 [1.31745482 0.81145064]
 [2.04456298 0.93022696]
 [0.86767598 0.29988495]]
